### ISSUE TITLE
Themes don't work on 12.1.0

### ISSUE THREAD

**Issue by Pauljr456** [exelix11/SwitchThemeInjector#89]
Themes on home page don't work causes atmosphere to crash

**Comment by exelix11** [comment]
There's already a fix on its way in #88 , you can find a test build [here](https://github.com/exelix11/SwitchThemeInjector/actions/runs/1005574785). I'll make a new release tomorrow.

**Comment by Pauljr456** [comment]
Thank you it worked!

**Comment by ELY3M** [comment]
great to hear this.

**Comment by ELY3M** [comment]
try to compile this with latest libnx esp version with old hid removed. 

I am getting those errors. 

linking SwitchThemesNX.elf
d:/devkitpro/devkita64/bin/../lib/gcc/aarch64-none-elf/11.1.0/../../../../aarch64-none-elf/bin/ld.exe: D:/devkitPro/portlibs/switch/lib\libglfw3.a(switch_joystick.c.obj): in function `_glfwUpdateSwitchJoysticks':
switch_joystick.c:(.text._glfwUpdateSwitchJoysticks+0xc): undefined reference to `hidScanInput'
d:/devkitpro/devkita64/bin/../lib/gcc/aarch64-none-elf/11.1.0/../../../../aarch64-none-elf/bin/ld.exe: switch_joystick.c:(.text._glfwUpdateSwitchJoysticks+0x14): undefined reference to `hidKeysDown'
d:/devkitpro/devkita64/bin/../lib/gcc/aarch64-none-elf/11.1.0/../../../../aarch64-none-elf/bin/ld.exe: switch_joystick.c:(.text._glfwUpdateSwitchJoysticks+0x20): undefined reference to `hidKeysHeld'
d:/devkitpro/devkita64/bin/../lib/gcc/aarch64-none-elf/11.1.0/../../../../aarch64-none-elf/bin/ld.exe: switch_joystick.c:(.text._glfwUpdateSwitchJoysticks+0x2c): undefined reference to `hidKeysUp'
d:/devkitpro/devkita64/bin/../lib/gcc/aarch64-none-elf/11.1.0/../../../../aarch64-none-elf/bin/ld.exe: switch_joystick.c:(.text._glfwUpdateSwitchJoysticks+0xdc): undefined reference to `hidTouchCount'
d:/devkitpro/devkita64/bin/../lib/gcc/aarch64-none-elf/11.1.0/../../../../aarch64-none-elf/bin/ld.exe: switch_joystick.c:(.text._glfwUpdateSwitchJoysticks+0x124): undefined reference to `hidTouchCount'
d:/devkitpro/devkita64/bin/../lib/gcc/aarch64-none-elf/11.1.0/../../../../aarch64-none-elf/bin/ld.exe: switch_joystick.c:(.text._glfwUpdateSwitchJoysticks+0x134): undefined reference to `hidTouchRead'
d:/devkitpro/devkita64/bin/../lib/gcc/aarch64-none-elf/11.1.0/../../../../aarch64-none-elf/bin/ld.exe: D:/devkitPro/portlibs/switch/lib\libglfw3.a(switch_joystick.c.obj): in function `_glfwPlatformPollJoystick':
switch_joystick.c:(.text._glfwPlatformPollJoystick+0x38): undefined reference to `hidIsControllerConnected'
d:/devkitpro/devkita64/bin/../lib/gcc/aarch64-none-elf/11.1.0/../../../../aarch64-none-elf/bin/ld.exe: switch_joystick.c:(.text._glfwPlatformPollJoystick+0x64): undefined reference to `hidKeysHeld'
d:/devkitpro/devkita64/bin/../lib/gcc/aarch64-none-elf/11.1.0/../../../../aarch64-none-elf/bin/ld.exe: switch_joystick.c:(.text._glfwPlatformPollJoystick+0xf0): undefined reference to `hidJoystickRead'
d:/devkitpro/devkita64/bin/../lib/gcc/aarch64-none-elf/11.1.0/../../../../aarch64-none-elf/bin/ld.exe: switch_joystick.c:(.text._glfwPlatformPollJoystick+0x100): undefined reference to `hidJoystickRead'
collect2.exe: error: ld returned 1 exit status
make[1]: *** [/opt/devkitpro/libnx/switch_rules:80: /e/windev/SwitchThemeInjector-own/SwitchThemesNX/SwitchThemesNX.elf] Error 1
make: *** [Makefile:174: build] Error 2

**Comment by ELY3M** [comment]
I had to downupgrade libnx and I am able to have all of my themes parts working :)

**Comment by exelix11** [comment]
@ELY3M Your problem is most likely outdated portlibs, you updated libnx but still using old glfw.

Anyway, [release](https://github.com/exelix11/SwitchThemeInjector/releases/latest) with 12.1 support is now up
